-- AlterTable
ALTER TABLE `user` ADD COLUMN `balanceG` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `balanceP` DOUBLE NULL DEFAULT 0,
    ADD COLUMN `firstName` VARCHAR(191) NULL,
    ADD COLUMN `lastName` VARCHAR(191) NULL;
